In [1]:
ls

 磁碟區 C 中的磁碟沒有標籤。
 磁碟區序號:  4A1C-CA0E

 C:\Users\PeiYu\dm\TKU-DM-Class 的目錄

2022/09/29  上午 10:20    <DIR>          .
2022/09/22  上午 11:05    <DIR>          ..
2022/09/29  上午 10:20    <DIR>          .ipynb_checkpoints
2022/09/22  上午 11:40             9,194 0922.ipynb
2022/09/29  上午 10:20                72 0929.ipynb
2022/09/22  上午 11:05               908 Hello.ipynb
2022/09/29  上午 10:00            12,356 Numpy.ipynb
2022/09/22  上午 11:05                14 README.md
2022/09/22  上午 11:37           152,257 scores (1).csv
2022/09/22  上午 11:05               409 scores.csv
2022/09/22  上午 11:05             6,271 Untitled.ipynb
               8 個檔案         181,481 位元組
               3 個目錄  717,198,389,248 位元組可用


In [2]:
run Hello.ipynb

Hello!


In [5]:
%%writefile hi.py
print("Hi 0929!")

Overwriting hi.py


In [6]:
run hi.py

Hi 0929!


In [7]:
a = 1

In [8]:
b = 2

In [9]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [10]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [12]:
np1 = np.array([1,2,3,4])
np2 = np.array((5,6,7,8))


In [13]:
np1

array([1, 2, 3, 4])

In [14]:
np2

array([5, 6, 7, 8])

In [15]:
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [16]:
np3 = np.arange(0, 31, 2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [17]:
np3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [18]:
np4 = np.linspace(1, 15, 3)

In [19]:
print(np4)

[ 1.  8. 15.]


In [20]:
np4

array([ 1.,  8., 15.])

In [21]:
np4 = np.linspace(1, 10, 10)

In [22]:
np4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np5 = np.zeros((5,))
print(np5)

[0. 0. 0. 0. 0.]


In [24]:
np5

array([0., 0., 0., 0., 0.])

In [25]:
np6 = np.ones((5,))
print(np6)

[1. 1. 1. 1. 1.]


In [26]:
np7 = np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [27]:
np7

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np7 = np.ones((5,3))
print(np7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
listdata = [[1,2,3,4,5],
       [6,7,8,9,10]]

In [30]:
listdata

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [32]:
np8 = np.array(listdata)

In [33]:
np8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
print(np8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print('維度', np8.ndim)

維度 2


In [36]:
print('形狀', np8.shape)

形狀 (2, 5)


In [37]:
print('數量', np8.size)

數量 10


In [38]:
np9 = np.arange(1,21)

In [39]:
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
print(np9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [43]:
np10 = np9.reshape(4,5)

In [44]:
np10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [46]:
np10a = np9.reshape(5,4)

In [47]:
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [48]:
np10b= np9.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [49]:
np10 = np.arange(0,9)
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[:4])
print(np10[4:])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3]
[4 5 6 7 8]


In [50]:
np11 = np.arange(1, 21).reshape(5, 4)

In [51]:
np11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [52]:
print(np11)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [53]:
np11[0, 2]

3

In [54]:
np11[0, 3]

4

In [55]:
np11[1, 2]

7

In [56]:
print(np11[1:3, 2])
print(np11[1:3, 1:3])
print(np11[::2, ::2])
print(np11[:, 2])
print(np11[1, :])
print(np11[:, :])

[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[ 3  7 11 15 19]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [57]:
print('1.產生2x3 0~1之間的隨機浮點數\n',
      np.random.rand(2,3))
print('2.產生2x3常態分佈的隨機浮點數\n',
      np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
      np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
      np.random.randint(2,5,[5]))
print('5.產生3個 0~1之間的隨機浮點數\n',
      np.random.random(3),'\n',
      np.random.random_sample(3),'\n',
      np.random.sample(3))

1.產生2x3 0~1之間的隨機浮點數
 [[0.06372775 0.9295176  0.64126234]
 [0.22661506 0.21054886 0.60987101]]
2.產生2x3常態分佈的隨機浮點數
 [[-0.25887383 -0.69156787  0.58169129]
 [-0.49848117 -0.00629931  1.22501806]]
3.產生0~4(不含5)隨機整數
 0
4.產生2~4(不含5)5個隨機整數
 [2 4 4 4 3]
5.產生3個 0~1之間的隨機浮點數
 [0.55662926 0.44645724 0.31582168] 
 [0.23955766 0.85320987 0.88766383] 
 [0.59562612 0.42315716 0.50719735]


In [58]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [59]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [60]:
print(np12.shape)

(30, 4)
